### ISSUE TITLE
scaling changes aspect ratio of the markers.

### ISSUE THREAD

**Issue by yayatinaresh** [burghoff/Scientific-Inkscape#11]
While scaling the plots to different aspect ratios then they originally come from the plotting platform, the marker aspect ratios look quite bad. It would be good if there is a way not to affect the markers.

**Comment by burghoff** [comment]
There is. In the Advanced tab, there is a section to add Exclusions, which you can use to change how objects are scaled. It was primarily designed with markers in mind. It lets you leave markers either completely unscaled, or alternatively scales them with a locked aspect ratio.

1. Select the items you would like to exclude
2. Change Exclusions to "Unscaled" or "Scaled with locked aspect ratio."
3. Run Scale Plots with the Advanced tab selected.
4. Unselect them and run in Scaling/Matching/Correction mode as normal

**Comment by yayatinaresh** [comment]
Thanks for the answer. **That solved my problem**. Bit tedious though to select all markers manually as my plot have several of them. I tried to combine by color, which works like a charm.

**Comment by burghoff** [comment]
Yes, ultimately there's nothing in SVG to differentiate markers that you wouldn't want to scale from lines that you do want to scale—they're all just paths. But Combine by Color is meant to make it a little easier.
