### ISSUE TITLE
Make it installable within the Extension Manager

### ISSUE THREAD

**Issue by gyger** [burghoff/Scientific-Inkscape#2]
There seems to be a Extension Manager in recent Inkscape versions. Would be great if that extension could be installable through that one.

**Comment by burghoff** [comment]
Sure, I'll see what it takes to get it added.

**Comment by burghoff** [comment]
Good news: I just got it added. (Had to jump through some hoops first.) If you download the 1.2 beta, it should be available in the Extensions Manager.
