### ISSUE TITLE
Autoexporter PDF export bugs

### ISSUE THREAD

**Issue by kjohnsen** [burghoff/Scientific-Inkscape#21]
It looks like the autoexporter is doing some funky things with diagram connectors and with super thin rounded rectangles. This doesn't happen with normal PDF export.

Original:
![image](https://github.com/burghoff/Scientific-Inkscape/assets/19983357/8062e3b2-9a32-4d39-bd72-10ed9f3b8ac2)

PDF export:
![image](https://github.com/burghoff/Scientific-Inkscape/assets/19983357/6cecf6db-b358-48af-9fa7-9c4ef9059ae8)

**Comment by burghoff** [comment]
Thanks for the report. Can you tell me what Advanced options are you using for the export? E.g., are you converting strokes to paths?

If you could include an SVG, that would also be helpful—just delete the parts that aren't causing problems.

As a temporary workaround, anything that's causing problems can be marked for rasterization.

**Comment by burghoff** [comment]
I couldn't replicate it based on what's described. 
[Test_rects.pdf](https://github.com/burghoff/Scientific-Inkscape/files/12818623/Test_rects.pdf)
![Test_rects](https://github.com/burghoff/Scientific-Inkscape/assets/47142355/a1a0de77-7340-41d0-8373-c2cc51d1744c)

Likely there's something specific about your SVG causing the issue. I will need it to do further investigation. You don't need to give me the whole thing if you don't want, just save a copy where you delete the parts of it that are not causing problems.

**Comment by burghoff** [comment]
Thanks, I was able to replicate. I'll fix the issue.

Thin line enhancement is an unfortunate rendering feature of many PDF viewers. Acrobat is the worst, but to some extent many do it. It causes certain thin paths to be displayed as wider. Example below (note the ls):
![image](https://github.com/burghoff/Scientific-Inkscape/assets/47142355/aca5927b-25a1-42dd-89aa-1cc00479b5e0)

The feature in the Autoexporter prevents this from happening.

**Comment by burghoff** [comment]
Ok, both issues have been fixed.

If you want the fix, it's currently on the dev branch: https://github.com/burghoff/Scientific-Inkscape/tree/dev
