### ISSUE TITLE
Autoexport failing to export opacity of group

### ISSUE THREAD

**Issue by kjohnsen** [burghoff/Scientific-Inkscape#23]
*Thanks for fixing the last autoexport bug, by the way. This looks to be a different one.*

**Describe the bug**
When I make a group of objects semi-transparent in the layers and objects tab, they are exported as opaque

**To Reproduce**
1. Create a group of objects
2. Make group (not individual objects) semi-transparent from the objects and layers tab
3. Run the auto-exporter extension 
4. See that exported PDF exports the group as opaque

**SVG attachments**
Please attach the SVG that caused the issue. If the issue is Autoexporter-related, also attach the output. This is crucial for most bug reports—without them most bug reports cannot be investigated.

![autoexport-test](https://github.com/burghoff/Scientific-Inkscape/assets/19983357/e29e2c49-cec0-4142-9eb5-fd6103b70f06)
[autoexport-test.pdf](https://github.com/burghoff/Scientific-Inkscape/files/14101085/autoexport-test.pdf)

**Inkscape version:**
1.3.2

**Additional context**
On dev branch of Scientific Inkscape

**Comment by burghoff** [comment]
Thanks for the bug report. It's fixed now and on the dev branch if you want to try.

(Behind the scenes, the Autoexporter is taking some steps to try and prevent MS Office products from rasterizing transparent objects. In this case, the fix was being applied inappropriately to groups.)

**Comment by kjohnsen** [comment]
Groovy. Thank you!
