### ISSUE TITLE
Autoexporter bug: marker transparency

### ISSUE THREAD

**Issue by kjohnsen** [burghoff/Scientific-Inkscape#25]
**Describe the bug**
Markers don't get exported as transparent along with the line.

**To Reproduce**
1. create a line with an arrow marker
2. set line to semi-transparent
3. autoexport
4. see resulting PDF has semi-transparent line, but not arrow marker

**SVG attachments**
![autoexport-arrow-bug](https://github.com/burghoff/Scientific-Inkscape/assets/19983357/e7ddc2aa-0b85-47ca-856b-b9aa180eab25)

**Screenshots**
From resulting PDF:
![image](https://github.com/burghoff/Scientific-Inkscape/assets/19983357/e63db383-1f83-43e5-8db7-595f65eddcb5)

**Inkscape version:**
 1.3.2

**Additional context**
On commit 6763d780c6c634af8becbb1c8405c35d5a5e6638.

I'm trying both setting the whole arrow opacity as well as setting the stroke paint. Doing the latter I see even in the Inkscape interface that the marker doesn't change opacity with the rest of the path. Maybe it's an Inkscape problem

**Comment by burghoff** [comment]
I'll look into it, thanks.

Did you solve the TextParser / parser issue? I just want to double check since that would break almost everything. (I'm preparing to move my text submodule into Inkscape, since the extension handler doesn't have that functionality and it would help free me of scrambling before each new release.)

**Comment by burghoff** [comment]
Also, until I fix the issue you can just rasterize the offending path (Autoexporter > Rasterizer). That 'solves' most export issues.

**Comment by kjohnsen** [comment]
I did solve the TextParser issue. I had just failed to copy all the code `cp -r` into the extensions folder. I did a workaround by converting stroke to path for the moment.

**Comment by kjohnsen** [comment]
It's working!
