### ISSUE TITLE
feature request: export pdf_tex

### ISSUE THREAD

**Issue by wandida** [burghoff/Scientific-Inkscape#5]
greetings,

would it be possible to include the export as pdf_tex feature of inkscape to the autoexport function?
it would make my life a lot easier :)

best regards,
david

![grafik](https://user-images.githubusercontent.com/122943487/213035058-783af768-c826-447e-96df-a54c71cd377a.png)

**Comment by burghoff** [comment]
It is doable, but as I am worried about feature creep I will have to think about how to best add the option.

For now, I just uploaded a new version of [autoexporter.py](https://github.com/burghoff/Scientific-Inkscape/blob/main/scientific_inkscape/autoexporter.py) that allows you to enable the pdf_tex feature manually. Just change line 20 to `PDFLATEX = True` if you want to enable it.

Let me know if it's working for you.

**Comment by wandida** [comment]
that works perfectly, thank you

**Comment by burghoff** [comment]
FYI, I officially added the option in the latest release.

Just curious, but how do you use those files in your workflow? When doing LaTeX I just keep the text as is in my PDF figures. Is it just to ensure that the font matches the rest of the LaTeX document?

**Comment by wandida** [comment]
yes, the font, fontzize and equations. Also for fancy stuff like pdf tipps or glossary
