### ISSUE TITLE
Incomplete terminal listing and string to byte string comparison

### ISSUE THREAD

**Issue by razimantv** [burghoff/Scientific-Inkscape#7]
The terminal list in autoexporter.py is a list of strings, while comparison is done with byte strings.

https://github.com/burghoff/Scientific-Inkscape/blob/a40e57c48e35714c23896ef84778569b12bf7ca4/scientific_inkscape/autoexporter.py#L242-L257

My understanding is that [strings do not equal byte strings in Python3](https://stackoverflow.com/q/30580386).

Additionally, the terminal check is only done for gnome terminal and x-terminal-emulator, neither of which I have (only konsole).

**Comment by razimantv** [comment]
I have made a pull request #8 to solve the string comparison issue, but I have been unable to get the exporter working with konsole.

**Comment by burghoff** [comment]
Thanks, I test infrequently on Linux. Did you try adding a case like the following?
```
    elif t == "konsole":
        LINUX_TERMINAL_CALL = "konsole -e bash -c '%CMD'"
```
Also, what version/installation are you using? I couldn't get Snap and AppImages to work at all, and all of the recent versions seem to be one of those.

**Comment by razimantv** [comment]
This is the error I see on gnome-terminal when I save the file in Inkscape, BTW:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/razimantv/.config/inkscape/extensions/autoexporter_script.py", line 268, in run
    offset = round(os.get_terminal_size().columns/2);
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by burghoff** [comment]
Can you change that line to offset=50 to see if that fixes it?

Also, since all of the recent versions of Inkscape on all platforms come with Python GTK bindings, I have been thinking about using that to make a simple GUI, which should also work on all versions of Linux.

**Comment by razimantv** [comment]
Yes. I had removed the offset lines altogether and it worked. Setting offset to 50 works too. The terminal is empty (does not show the expected print statements), but the file gets autosaved.

**Comment by burghoff** [comment]
On the dev branch I added new versions of [autoexporter.py](https://github.com/burghoff/Scientific-Inkscape/blob/dev/scientific_inkscape/autoexporter.py) and [autoexporter_script.py](https://github.com/burghoff/Scientific-Inkscape/blob/dev/scientific_inkscape/autoexporter_script.py) that uses the built-in GTK instead of the terminal business. It should greatly improve Linux compatibility. Would you mind trying it out?

**Comment by razimantv** [comment]
Thank you, that works perfectly.

The directory was a bit polluted with extra package directories etc. I removed those and it still works.

**Comment by burghoff** [comment]
The packages are for the new Powerpoint extractor extension I've been working on, so they don't matter for the others.
